/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Shape1(props) {
  const { nodes, materials } = useGLTF("./assets/shape1.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shape1.geometry}
        material={materials.Holographic}
      />
    </group>
  )
}

useGLTF.preload("./assets/shape1.glb")
