/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Shape3(props) {
  const { nodes, materials } = useGLTF("./assets/shape3.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape3.geometry}
        material={materials.Holographic3}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={1.863}
      />
    </group>
  )
}

useGLTF.preload("./assets/shape3.glb")
