/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Shape4(props) {
  const { nodes, materials } = useGLTF("./assets/shape4.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shape4.geometry}
        material={materials["Holographic.001"]}
      />
    </group>
  )
}

useGLTF.preload("./assets/shape4.glb")
