/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Shape2(props) {
  const { nodes, materials } = useGLTF("./assets/shape2.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shape2.geometry}
        material={materials.Holographic2}
        rotation={[-0.006, -0.122, -2.73]}
      />
    </group>
  )
}

useGLTF.preload("./assets/shape2.glb")
